project = xessdemo
vendor = xilinx
family = spartan6
part = xc6slx9-tqg144-2
top_module = all_leds

#libdir = ../../fpgamiddlewarelibs
#libs = MiddlewareController
vfiles = ../src/all_leds.vhdl
ucffile = ../src/PapilioDuo.ucf
bmm_file = ../src/xessdemo.bmm

include xilinx.mk
