project = middleware
vendor = xilinx
family = spartan6
part = xc6slx9-tqg144-2
top_module = top

libdir = ../../fpgamiddlewarelibs
libs = IcapInterface
vfiles = ../src/main.vhdl
ucffile = ../src/PapilioDuo.ucf
bmm_file = ../src/xessdemo.bmm

# remote_path = git/fpgamiddlewareproject/

include xilinx.mk