# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7s50ftgb196-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/alwynster/git/fpgamiddlewareproject/fpgamiddlewareproject/fpgamiddlewareproject.cache/wt [current_project]
set_property parent.project_path C:/Users/alwynster/git/fpgamiddlewareproject/fpgamiddlewareproject/fpgamiddlewareproject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/alwynster/git/fpgamiddlewareproject/fpgamiddlewareproject/fpgamiddlewareproject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library neuralNetwork {
  C:/Users/alwynster/git/fpgamiddlewareproject/src/Common.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/ConnToVector.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/Distributor.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/sumMux.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/Sigmoid.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/Neuron.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/Layer.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/bram_tdp.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/VectorToWeights.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/WeightsToVector.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/VectorToConn.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/HiddenLayers.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/FixedPointANN.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/FixedPoint_Logic.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/Logic_FixedPoint.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/SignedANN.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/SignedANNSkeleton.vhd
}
read_vhdl -library fpgamiddlewarelibs {
  C:/Users/alwynster/git/fpgamiddlewareproject/src/fpgamiddlewarelibs/UserLogicInterface/UserLogicInterface.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/fpgamiddlewarelibs/UartInterface/uartInterface.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/fpgamiddlewarelibs/IcapInterface/icapInterface.vhdl
  C:/Users/alwynster/git/fpgamiddlewareproject/src/fpgamiddlewarelibs/UartInterface/uart_rx.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/fpgamiddlewarelibs/UartInterface/uart_tx.vhd
}
read_vhdl -library xil_defaultlib {
  C:/Users/alwynster/git/fpgamiddlewareproject/src/InterfaceStateMachine.vhd
  C:/Users/alwynster/git/fpgamiddlewareproject/src/middleware.vhdl
  C:/Users/alwynster/git/fpgamiddlewareproject/src/genericProject.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/alwynster/git/fpgamiddlewareproject/elasticNode.xdc
set_property used_in_implementation false [get_files C:/Users/alwynster/git/fpgamiddlewareproject/elasticNode.xdc]

read_xdc C:/Users/alwynster/git/fpgamiddlewareproject/src/GenericProject_spartan.xdc
set_property used_in_implementation false [get_files C:/Users/alwynster/git/fpgamiddlewareproject/src/GenericProject_spartan.xdc]


synth_design -top genericProject -part xc7s50ftgb196-2


write_checkpoint -force -noxdef genericProject.dcp

catch { report_utilization -file genericProject_utilization_synth.rpt -pb genericProject_utilization_synth.pb }
